---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inventory-secret
  namespace: vortex
spec:
  encryptedData:
    DATABASE_URL: AgDBhZtogdBQVngKqrBUP3FlH8mp4hC7v9Ya2McY9uW+VzaLT+c37BBnsOoQmIlAaxSZcVCCuu809TJP3QsrYYBWBXzs7JG+QK17QLLxSFR2ZtuE0kKWQaj1LgQEFMvWOz87J+bUhBJbkjc2TBFBlAKRRcNIxmFwpBOJBfVfo+lbZ0HLLnlSkhmMku0MxrdFpjmbioBlPylRmq1+p/TAbrT4VDjU0PejOIAGFSUQOTiAf6EKSMa+x/6eW8WukZfb90fSubYTMTR7K3fq3M+CvNdqe77o5WStpA0Td2a8lmjLcPA2UQqR1tx1kyj0rwZypV63X0UL7DEw60DCEItjmw06mVbVcx4WHvFDXXf98oIcbA3bsCPxQBbwRNGtqmKplk68cblBitvkWck9VbzygbVZtfr3+tofeR/GDtpvauPyt3kXQ10SWQ1y+3tYZX+btWRJx4+wPzJgEhaBEme01w352SqsByNYBO5JR6WKNIc1kTz6GyOFm+7Ev3jQzr4gvgBsBY3DJd7+gYUS8L19XHVcq9YO6fOKCso43MZOYOnKDaLtOglTYFfs1fUiJocjmUWYKAChXgvN+md3NFgSSHELN255WilsMDA28s9R4Cm37EeWt2c2IXYOZyiINljKq2P8oxRNKaDuBs2Ojz5k8sIurYDOru4+jp/kdGhs1tNxjTx88o43a5IOJ5NaiwZlHo8P7Fr9k3FqNz35r9gNzz5X0XsgZLNhjL32hzn0Oziaatbfp7RQCefe/s7ABBbI9Rx8oXsV8R0dwa9KOXq/
  template:
    metadata:
      name: inventory-secret
      namespace: vortex
    type: Opaque
