---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inventory-secret
  namespace: vortex
spec:
  encryptedData:
    DATABASE_URL: AgBhSWjVBSsA42dX2Mgl20h56CK/cBIb7lgA2oKv+SPBNALzgr5a1Y054VxR8FQVm3c22icuCzM/IZ1UlSNjVBqj/lKrhmOGqFQGEXB1jeF/GZdnW/V8Cx1gr8xe1hxfp3OrsYIus5KxAM+Hd9Bs2Fw/BuamyXf6F9VW4l6xMYsZqQWPPQhK5M4MBcHd33PgIVlL4ZQH6rR6Ya68qmWTZJ0JoarWSqVGOzblU0kEiE076+nbQ9Am4WQ7e7Uq9QW2ReiUYsgULOOQvuDXyjVzveK9WmdqJv2V2cBBBjO5MRWC/N8Bogb2CD1fT07VJTg/OxLwzOgidJliDSdr/dmoXNCxd6L9s9W0oX3rBEhs/DMKx+6oFNe3clNrop2nkkHQPpePu3BHBYp1WGlw+nfjhJE3scga1cBq4bcIlDd6H0Gzu2qOl5vnyLP+ER8SAgqEd7yXCCOmi6FZzh8AQvzzQJ7d3/BEF6MXwsBEOUlokaFVHff10U5h+8b9ljAB1v/rdM7sMbBXXHhayDDC63wNou/sMyepG5cPdFSvumr3T+xGmhMSvqzAdjmCs34aCm6YhQpEMDwMan2mRtOPZ84Ikt6YqAziMV+2SEmjObZ8Gc9rlGdi8Hu4qkoutDmw4znOMilM2Dd3sH3PdN3UksUsZpI+BXi5pzIhnONMdvsFNjkOeXA27xQahHRvTl86EwMIbPX317xBNjyHDE4nEPbXVnbRpFCb8UOztSW9RAyi275AZ0QrYkoiwAq7y8AWO+lUMoFtgKvOnZWzOtjQx8th
  template:
    metadata:
      name: inventory-secret
      namespace: vortex
    type: Opaque
