---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-secret
  namespace: vortex
spec:
  encryptedData:
    DATABASE_URL: AgA7uM4lL1FMxqrTsNwZxJiIBIDXY+5m6dAOo2IJ+oha2d2PGSBWWzbe404/BICGAC3QOzGR9Rwsh6+M+Vt569FjoSirS/10eb7/RqSTrA76AzpohOj2chDRZrab/T/8XUnDCMCsRYBASM4xUDs0UgtWGIe9dCaRabXQ2hw5P39ckumaLMmYNlwnj4b23Oza2rseTMGrz/sqlIm6FnOvF9+A7S/3AEWZ27QNU5pslIZtQN8lA6NFA6vcYLHt8cwYTHcgiRqOmKHPoZpqEiIC6Hi0TFO3RsPLQLt1We1Wa1A5ZMbNUG8QOEIKS4qNXdSeMMFZ/47hiH0mtaZbyD3VRNQs5WuOE7WGdclS6wTVhVR9I+N+eUqIdEuz3C7tMy8jaXPYnWDz0Dpzw+AYjeXXX8EE2alzKHBuzLkz2sFgQDOCChHzi2UWGi8ChDBAmdJ7qx57el+adI1Hq+/rclZ9kFwRUMbb7N55SsQdGbKPyUv/a534R/hXFJV5DxN061IPQT3ddFCJ/gbuWK4VH32VIxqRaWA+tyU3l5dtxcg0I1W7omF/ChMxWUifjnHm9Un2sM22V7i2lg5iL52JTFRQZiwn2+ACZ97JohC/aQ8W97S5wABEjZxJWfJ+C8YfRpm4zNbMcthZt71/cPcxoGffYe64+/kYv6wAhYDefNqkUpHHHLT8FxolOmoV4HxLiGgNxsFFS7RQwtIViz0zcrv0LpF6fHd0l3Hm+6P65qJ40RKp/IsrSdqqBU2No4CpoMvlrLcn7cEc
  template:
    metadata:
      name: orders-secret
      namespace: vortex
    type: Opaque
