---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-secret
  namespace: vortex
spec:
  encryptedData:
    DATABASE_URL: AgCpktgyQRmhY+nmeHoMIPSuiQl4ZUYEH4/6veF0Y2LsjnngO89FurTQmtqlXXkvk9NCaT8Q0R8aOSiYa6hrTVefPdTF2tANWdZmueNo8vfoN2dquaSa9F8UqMp7Bd8dr/acoShlmNyooQkwGLkefVyr14AUqwQ/BBXM9rqpp/Bhb5lzMLRIY61ApPzLi6G7N3VsZywO2u0KUo4SmPFm0RVcHsamITzMtQpivCsdF4tD4HWiJMBeCKqXoO+UQxMSqCasYKlebscjriavI7oa9VXFv8HkTGMcdBoUdWPhI5ppLB37Q2Jvl/bOaQssy+lPz0J4ox7zJ2jnTvXdEsYFVEu9DRtmBVYNnHJXrzoO8eSFhHIGL+VjJLCnuIsZx4Unv1GSJk8Lh7szFdPNUMxYo84pCChM54CiTES57B8TJZ54DKg8Do0FO7318dCUU3pkDfZRnJeMixyeNHx7RD3Pfn7+sIK+FiZv+IWQJh1tUDOajAWdhefrLnKBEss96tHTcLrbX4Ts8HMwkKzFu6e1Qes7lXci98J1Bi31Q0QEi9KlyjBNPWiRjJcIinwp7wEoqYg9wG1cEJ6BZ4+587VxgoSF8pXpO+X2DFo6EwLgPH4Ypx3onh5Tpi60eshWK/2BZ29JY3wdberjonjD9WwN4d/3wjYC7Lq5AaY8ya70laTGhTV7lizMwfa+dMpiHnrucokcTdkXdjjeCoKlq7ZODEQCEbvvdGzXhjlS/1I7jURxa//DVx1Utey2SomaZ/GZu7+V4iqW
  template:
    metadata:
      name: orders-secret
      namespace: vortex
    type: Opaque
