---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: vortex
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA3No9sEZT8xOkLAbFgOWAm2vHJut3NcgEhDgXnglWu4ak0DI3T2ith0co2KooZSGHh/MTbaMEv9sWOCJDUVIBBUB+IkE2nozjXlJ4yhsHK5zjUZkjzoEDKtuuykz4t84Wtw3XyT3FLlqol+y7dsPxxxu3LlXoJYPnsclX6bx5MSKKao3ILlAL6xMC+Oqnqsa1LZ9djAzu5sgrZHubLrKAnX5vZFMr7KfMMkMNLWTo1PdOeaEvzzjXbIuof1GdXGhwaqineh77KysYYr/maZicx5wLQeCOB2RAHrIXrdZVE3hwtVHrGxcyYRR3XOLukBfTWDfEwVpZjJ21puhpeWaIi1R4RB8TpVssFuHVLUT5euX6senmFqQ3ovOGzIKAecfW80lZxhXS6emtYh/BW+idKBVElRqcjQOsx1VssnwGTLcqroO3XbHVBFNQDUlbqI4bxmg+Z4ifYObFO0VWf3RS4hpzEBzRKhudYU+X8DvtuK21DuTm4AMH3dNA+ptCwS2RV+aajkel5d4uc6MsKPmpDmhVlDZH49N6y0uHnaoaohmBL5gQmM2jVi3U5rAleLEdhOFMg9CqDCk/k/RkbOvNEyDTyqW0TV4rZ9mL9LYFqtBxnVYhFVGMpFiAbYuOG1dVakfFSx4CHB6dsTlhgHbGGCWst1qtCzmlwgYU8x18/WJ7+N96J5riqumgycQbLqYXPSIMaLBxRXA==
    POSTGRES_USER: AgAubzQa8veP/y9dPtbEbsiCQ0C4ZMkVH42SYvk3CpUGu8xnX7gF+8QffXjdpuUdWwr7nnD4IXdbLwa+DGo7/pl7woRB0cnyhXTojXvORZplqQfyWTHdUUi1vcbV4TnHl0lBNZv9+tywmivtWla0nTOAEZoAgRlNIT2DD3yBXTSoTPeibqvJavRS8IOKXw1HwR80SJ9acwPE0j0AATrGfNhP11DtaVredbPvy5FmbwO9TEEIEPR+hIS0Bw5xMBpxsDi9ujUwPH8rb6ADsgmKThbw/iHmWxnlWTVjTOjtMtiFfmv2KN6s4nU8Pc37ydtlJXMsQlR8zRrITGzB8/8NojLDfL3D6vaMNAGbuxr7OlD4NVNrZiojCONANGhdqrvAqNk259/GZvZowAQkDBqvIj0LjfTW1dpMcNJPp5tNELSH/8xhBbtlWTR2tNL3JvikhtGfVs9rviyeZ4mDkgicIkgw5VMXrllyZ7SOLVlm66XtQDvYz0csxfsWCOwzUntjSnWZIhvRezWK2JGulIPCAajS5Dv35758muEFegk8AWpbzUkbK38IKPuYR4KgRlBpYSSE5JcQk2QVJWfEeL1J4oOZ6SmJestVXkjrFn0EP0YE0tGOULV14JIWahcWDcd8zCPWaCuc4IVaoeVactYKDJr62K8W3eUypB+rZtF/IpB582ECojpwwoF6aEGqB95h8d1Aflme22Zd5g==
  template:
    metadata:
      name: postgres-secret
      namespace: vortex
    type: Opaque
