---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: vortex
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCGEUxxlC2Ce/T0X883Bg2aeqm40joFMmZ4ULdxY3hwQ3i1+Pza31+Di7NH8R2k7YfC8hai4JNHxl/rIkyYjaPrOFmgfNHbBGW4dZHs7EuANa6bIphi2TFFk+7DXePFvClj4jAJ+7V8Dwe3W5ty9B0b7lO5ummCsc8hRQOLrgZEiTKe/xPqNfdPzOqh2kqhqnggRtjj/0QFhixa+RPXvFIFCJyMcrujNDhnXcjvUkC0aGGrzjHlCC0N+fXPJMsA7thkKwJd4dx0Jq0roZJYuJrRzIj3GjmSUi5Ydvie+F/N7okQLu678KhmBmn2jd+8EAG3H8BxlmX6mfbC3+26ITJeR0lvBKbaakdAyOo/L7qkTJVgJVO6gGYwQtPAle9EOy1Bc6vHY6Rz7gaWZc37VZGqOPzCNQEZ1WgmcJVpuj2pKlYyIadQs5b4g1F/WKg7kGLlNfq+yOvaBCQIF3iPZx2zdjhLjf410q7Qg2FEEnxpjXDS8GX+N3Q34C71lKWHvtUy3C2U6rMk0HD+jTJNn4ZX168xl8zLVb0Hnuh1JEemniUrjWtlzcOGToOaHJhCmaJnyPhHnMmdIGiJItuCvNTUCNdqI58exvYu6fUt0/1UjtMeuyjCGAURfKmIvYbTeo2KluyYFM5SEgor15wMP6657GfjBZP0AP2uqBgjNTh+ZgivijDbDKiNdoNahzH6PrA+4XFJgJr5GQ==
    POSTGRES_USER: AgANe/s5VJQYthVMG4WWZToFFu1GFi68AEl5qFRSx38IbTqGfs6kAdwXTLmTVP2Qe/5s8Ms/9pQ8h6E8XS0iu6VMVp1ppvOlE91mHP745zEAj+eM3+lslfUO8ETDmNJroV7eI69zQEbDJFxjd+zXvir0cxST6BXnPgOumV8tWm68r6wK0hRLVr3hVCT33UCCwZlcAoTcLsWakziMYNFgS7kjOug5B4jDpiL+nIPYUFHi8+q9ywSYglR57XLd1SgY8v9KbtdExnwDQ1m22s5dHBPkq+YvUDL/1HDZw0E8NI/5TnP0tX70vr4adr/8KmBh5rM6+xmGeSp6UFfFnx2rKG7X71bbxiXa7LV7c1/L6qzluBBau94RlH3lJk2WCZOFZEzJ3HHNQhDWKyU5cdH8pLGSI/qbTkxlkNv7YWUQ2qtGVFaoqu4vb6Q7qvPXd9fieHYQ8rQA+4kqjYloW/jH/Y8Fx1/lLuC869/9k6Px4ffDEU6eEwHP9QnNZpDPpLYbDmZLKVpmb+H4DZUOgMBfrwJRqkchjEc7anvrhtokJyHlhZG1wdgWqFp6XkYe+VrCX9dRGUuoMimDJc2Ky/LmOSSBMZ3YbD8RKxe5XqT6QNdMyeTWca/B/HMRfL3hsFu1pxm+mS0FoPtHu6XGqP5BpNYqk5jkavdU/WooX+AjSiY4FJ7vGcaLqB/s7WRNe1eT7i+U2mFA7S1cpw==
  template:
    metadata:
      name: postgres-secret
      namespace: vortex
    type: Opaque
